on: push

name: CI

jobs:
  all:
    name: Build plugin
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
      - name: Install gstreamer1.0-gl (and transitive dependencies)
        # Need libgstreamer1.0-dev for gstreamer-1.0.pc
        # Need libgstreamer-plugins-base1.0-dev for gstreamer-video-1.0.pc
        run: sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-gl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cargo update to refresh cache
        uses: actions-rs/cargo@v1
        with:
          command: update
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Linting with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets -- -D warnings
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload plugin
        uses: actions/upload-artifact@v2
        with:
          name: GstGLLcms
          path: target/release/libgstgllcms.so
      - name: Upload lock file
        uses: actions/upload-artifact@v2
        with:
          name: GstGLLcms-cargo-lock-file
          path: Cargo.lock
